# Generated by Django 5.0.7 on 2025-09-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='page_visited',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
