# Generated by Django 5.2.6 on 2025-09-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mentorrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='program_images/')),
                ('brochure', models.FileField(blank=True, upload_to='program_brochures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
