# Generated by Django 5.2.6 on 2025-09-15 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_superuser'),
        ('core', '0006_remove_program_video_url_program_video'),
    ]

    operations = [
    ]
