# Generated by Django 5.2.6 on 2025-09-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='video_url',
        ),
        migrations.AddField(
            model_name='program',
            name='video',
            field=models.FileField(blank=True, upload_to='program_videos/'),
        ),
    ]
